dist: trusty
sudo: false

language: python
python:
  - "2.7"

notifications:
  email: false

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  pip: true
  directories:
  - "~/.platformio"

env:
  - TEST_PLATFORM="-e BOARD_TYPE_0"

before_install:
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}

install:
  # Install PlatformIO core
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
  #
  # Enable warnings-as-errors build option
  - export PLATFORMIO_BUILD_FLAGS="-Werror"

before_script:
  # Update PlatformIO packages
  - platformio update
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  #
  # Backup default configuration (used by restore_configs)
  - backup_configs
  #
  # Enable strict CI checking for PlatformIO
  - export CI=true


script:
  # Build every config
  #
  - restore_configs
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_0_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  # TX-only
  #- export TEST_PLATFORM="-e BOARD_TYPE_0_TX"
  #- build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_1_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  # TX-only
  #- export TEST_PLATFORM="-e BOARD_TYPE_1_RX"
  #- build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_2_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  - export TEST_PLATFORM="-e BOARD_TYPE_2_RX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_3_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  - export TEST_PLATFORM="-e BOARD_TYPE_3_RX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_4_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  # TX-only
  #- export TEST_PLATFORM="-e BOARD_TYPE_4_RX"
  #- build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_5_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  - export TEST_PLATFORM="-e BOARD_TYPE_5_RX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_6_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  # TX-only
  #- export TEST_PLATFORM="-e BOARD_TYPE_6_RX"
  #- build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_7_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  - export TEST_PLATFORM="-e BOARD_TYPE_7_RX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_8_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  - export TEST_PLATFORM="-e BOARD_TYPE_8_RX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  #
  - export TEST_PLATFORM="-e BOARD_TYPE_9_TX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
  - export TEST_PLATFORM="-e BOARD_TYPE_9_RX"
  - build_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
