name: Build ExpressLRS
on: [push, pull_request]
jobs:
  build:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO
      run: |
        platformio platform update
        mkdir -p ~/artifcats
        cd src
        export PLATFORMIO_BUILD_FLAGS=-DRegulatory_Domain_AU_915
        pio run --environment Frsky_TX_R9M_via_STLINK 
        pio run --environment Frsky_TX_R9M_via_stock_BL 
        pio run --environment Frsky_TX_R9M_via_WIFI 
        pio run --environment Frsky_TX_R9M_LITE_via_STLINK 
        pio run --environment Frsky_TX_R9M_LITE_via_stock_BL
        pio run --environment Frsky_TX_R9M_LITE_PRO_via_STLINK 
        pio run --environment Frsky_RX_R9MM_R9MINI_via_STLINK 
        pio run --environment Frsky_RX_R9MM_R9MINI_via_BetaflightPassthrough 
        pio run --environment Frsky_RX_R9MX_via_STLINK 
        pio run --environment Frsky_RX_R9MX_via_BetaflightPassthrough 
        pio run --environment DIY_900_TX_TTGO_V1_SX127x_via_UART 
        pio run --environment DIY_900_TX_TTGO_V2_SX127x_via_UART 
        pio run --environment DIY_900_TX_ESP32_SX127x_E19_via_UART  
        pio run --environment DIY_900_TX_ESP32_SX127x_RFM95_via_UART  
        pio run --environment DIY_900_RX_ESP8285_SX127x_via_UART  
        pio run --environment DIY_900_RX_ESP8285_SX127x_via_BetaflightPassthrough  
        mv .pio/build ~/artifcats/AU_915
        export PLATFORMIO_BUILD_FLAGS=-DRegulatory_Domain_ISM_2400
        pio run --environment DIY_2400_TX_ESP32_SX1280_Mini_via_UART 
        pio run --environment DIY_2400_TX_ESP32_SX1280_E28_via_UART 
        pio run --environment DIY_2400_TX_ESP32_SX1280_LORA1280F27_via_UART 
        pio run --environment DIY_2400_RX_ESP8285_SX1280_via_UART 
        pio run --environment DIY_2400_RX_ESP8285_SX1280_via_BetaflightPassthrough 
        mv .pio/build ~/artifcats/ISM_2400

    - name: Store Artifacts
      uses: actions/upload-artifact@v2-preview
      with:
        name: ExpressLRS-${{ env.GITHUB_REF_SLUG_URL }}-${{ github.run_number }}
        path: ~/artifcats/**/*.bin
      continue-on-error: true
